/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'customOrders' : IDL.Null,
  'portraitArt' : IDL.Null,
  'pencilSketch' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addGalleryItem' : IDL.Func([IDL.Text, Category, IDL.Text, IDL.Text], [], []),
  'claimOwner' : IDL.Func([], [IDL.Text], []),
  'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getGalleryItemsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'getOwner' : IDL.Func([], [IDL.Text], ['query']),
  'seedInitialGalleryItems' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'customOrders' : IDL.Null,
    'portraitArt' : IDL.Null,
    'pencilSketch' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'addGalleryItem' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'claimOwner' : IDL.Func([], [IDL.Text], []),
    'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getGalleryItemsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'getOwner' : IDL.Func([], [IDL.Text], ['query']),
    'seedInitialGalleryItems' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };