/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'customOrders' : null } |
  { 'portraitArt' : null } |
  { 'pencilSketch' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
}
export type Time = bigint;
export interface _SERVICE {
  'addGalleryItem' : ActorMethod<[string, Category, string, string], undefined>,
  'claimOwner' : ActorMethod<[], string>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getGalleryItemsByCategory' : ActorMethod<[Category], Array<GalleryItem>>,
  'getOwner' : ActorMethod<[], string>,
  'seedInitialGalleryItems' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];